### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by philsturgeon** [ErikWittern/openapi-snippet#31]
Swagger is the old name of OpenAPI but it's not been called that for ages. It makes it hard to find things, as people these days search for "OpenAPI Foo" not "Swagger Foo". Swagger is mainly just the trademarked name for the swagger.io toolsuite by SmartBear, so maybe a new name can be created. 

"HTTP Snippet" would be fine. Or "OpenAPI Snippet". Or something creative. 

Also if you'd like to bring this over to the new [OpenAPI Contrib](https://github.com/openapi-contrib/) org I'm starting up, you'd be very welcome. We can find you some folks to improve OpenAPI support, fix some bugs, generally ramp up the OSS efforts.

**Comment by ErikWittern** [comment]
@philsturgeon I think renaming to `OpenAPI Snippet` is the right move. This library did gradually add some OpenAPI 3.0.x support in the past.

I just published [OpenAPI Snippet](https://www.npmjs.com/package/openapi-snippet) to npm, and created a deprecation message for Swagger Snippet, informing of the name change. I will rename this repository as well.

**Comment by philsturgeon** [comment]
@ErikWittern great, thank you! If you'd like to submit the new project to OpenAPI.Tools I'd be happy to accept it :D
