### ISSUE TITLE
OpenAPISnippets let over const

### ISSUE THREAD

**Issue by povilass** [ErikWittern/openapi-snippet#36]
https://github.com/ErikWittern/openapi-snippet/blame/d31d79a19a22a3f08285f46fab81d8d63fc6299f/index.js#L202

const OpenAPISnippets = window.OpenAPISnippets || {}  <------- let over const

  // define that object
  OpenAPISnippets = {
    getSnippets,
    getEndpointSnippets
  }

can you fix issue where you can't redefine OpenAPISnippets because it's const and it fails of readonly property.

**Comment by ErikWittern** [comment]
@povilass Thanks for filing the issue, and @joe642 for the PR! I released a new version with the fix: https://github.com/ErikWittern/openapi-snippet/releases/tag/v0.8.1
